# Generated by Django 5.1.7 on 2025-04-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_alter_recipe_options_alter_step_options_and_more'),
        ('restaurants', '0002_alter_restaurant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipable',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipable', to='recipes.recipe')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipable', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
