# Generated by Django 5.1.7 on 2025-04-07 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_num_sessions'),
        ('swipables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='groups.group')),
                ('owner_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
                ('swipable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='swipables.swipable')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('owner_username', 'swipable', 'group')},
            },
        ),
    ]
