# Generated by Django 5.1.7 on 2025-05-04 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupfoodscore'),
        ('swipables', '0002_swipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('owner_username', 'swipable', 'group', 'session')},
        ),
    ]
