# Generated by Django 5.1.7 on 2025-03-27 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('composite_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('owner_username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('owner_username', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SendGroupInvite',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('composite_key', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to='groups.group')),
                ('receiving_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_group_invites', to=settings.AUTH_USER_MODEL)),
                ('sending_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_group_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('sending_username', 'group', 'receiving_username')},
            },
        ),
    ]
