# Generated by Django 5.1.7 on 2025-03-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
