# Generated by Django 5.1.7 on 2025-05-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_num_sessions'),
        ('swipables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFoodScore',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('session', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_food_scores', to='groups.group')),
                ('swipable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_food_scores', to='swipables.swipable')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('swipable', 'group', 'session')},
            },
        ),
    ]
