# Generated by Django 5.1.7 on 2025-05-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupfoodscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupfoodscore',
            options={'ordering': ['-score', '-session']},
        ),
    ]
